// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AInput: typeof import('ant-design-vue/es')['Input']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APopover: typeof import('ant-design-vue/es')['Popover']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    ATree: typeof import('ant-design-vue/es')['Tree']
    DeleteTwoTone: typeof import('@ant-design/icons-vue')['DeleteTwoTone']
    EditTwoTone: typeof import('@ant-design/icons-vue')['EditTwoTone']
    FileAddTwoTone: typeof import('@ant-design/icons-vue')['FileAddTwoTone']
    FileTwoTone: typeof import('@ant-design/icons-vue')['FileTwoTone']
    FolderAddTwoTone: typeof import('@ant-design/icons-vue')['FolderAddTwoTone']
    FolderOpenTwoTone: typeof import('@ant-design/icons-vue')['FolderOpenTwoTone']
    FolderTwoTone: typeof import('@ant-design/icons-vue')['FolderTwoTone']
    MyMenu: typeof import('./components/myMenu.vue')['default']
    ProcessMain: typeof import('./components/processMain.vue')['default']
    QuestionCircleTwoTone: typeof import('@ant-design/icons-vue')['QuestionCircleTwoTone']
  }
}

export { }
